### ISSUE TITLE
Can not create new instance of Mnemonic

### ISSUE THREAD

**Issue by ivanvoznyakovsky** [ggozad/mnemonic.js#4]
When I try to do 

```javascript
var m = new Mnemonic(<complexity>)
```
the following error is thrown:
Firefox: TypeError: 'getRandomValues' called on an object that does not implement interface Crypto.
Google Chrome and WebKit based browsers: TypeError: Illegal invocation

```javascript
    function createGetRandom(getRandomValues) {
        return function (bits) {
            var random = new Uint32Array(bits / 32);
            getRandomValues(random); // this line throws an error
            return random;
        };
    }
```

Version used: 1.0.1 and latest

**Comment by ggozad** [comment]
I am afraid I had forgotten to tag a new release.
Can you try with the (now) tagged 1.0.2 and let me know?

**Comment by ivanvoznyakovsky** [comment]
version 1.0.2 works

**Comment by ggozad** [comment]
awesome

**Comment by ivanvoznyakovsky** [comment]
thnx for quick reply
