### ISSUE TITLE
Wordlists?

### ISSUE THREAD

**Issue by mitra42** [ggozad/mnemonic.js#6]
Thanks for the library - has there been any thoughts of supporting alternative word lists, for example unless I'm missing something this wordlist is different from that used in bitcoin (BIP39)

**Comment by mitra42** [comment]
Oops - looks like this wouldn't work for BIP39 anyway since you use a different number of words. (BIP39 uses 2048). That's a pity since I'm looking for something like this to work between a python server and a javascript client  - and the common modules on Python  (e.g. the one called mnemonic)  use 2048 with the BIP39 list, while yours on Javascript uses 1626 with your own list and 
bitcoinjs/bip39 depends on nodejs or browserify (which is problematic on OSX).

**Comment by ggozad** [comment]
Hey,
I would suggest looking into bip39 since you want interoperability.
